# Generated by Django 6.0 on 2026-01-05 17:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroComercial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_winthor', models.CharField(blank=True, help_text='Código do cliente no sistema Winthor (apenas após conversão)', max_length=50, null=True, verbose_name='Código Winthor')),
                ('nome_empresa', models.CharField(max_length=200, verbose_name='Nome da Empresa')),
                ('telefone', models.CharField(max_length=50, verbose_name='Telefone')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
                ('origem', models.CharField(choices=[('base_winthor', 'Base Winthor'), ('google', 'Google'), ('site', 'Site'), ('instagram', 'Instagram'), ('indicacao', 'Indicação'), ('prospeccao_fria', 'Prospecção Fria'), ('whatsapp_ativo', 'WhatsApp Ativo'), ('outros', 'Outros')], help_text='Origem do lead. Não pode ser alterada após criação.', max_length=20, verbose_name='Origem')),
                ('status_pipeline', models.CharField(choices=[('importado', 'Importado'), ('contatado', 'Contatado'), ('conversou', 'Conversou'), ('interesse', 'Interesse'), ('pedido', 'Pedido'), ('perdido', 'Perdido')], default='importado', max_length=20, verbose_name='Status no Pipeline')),
                ('ultimo_contato', models.DateTimeField(blank=True, null=True, verbose_name='Último Contato')),
                ('resultado_ultimo_contato', models.TextField(blank=True, help_text='Breve descrição do resultado', verbose_name='Resultado do Último Contato')),
                ('proximo_passo', models.TextField(blank=True, help_text='Breve descrição da próxima ação', verbose_name='Próximo Passo')),
                ('data_conversao_cliente', models.DateTimeField(blank=True, help_text='Data em que virou cliente no Winthor', null=True, verbose_name='Data de Conversão')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('no_kanban', models.BooleanField(default=False, help_text='Indica se o registro está ativo no Kanban', verbose_name='No Kanban')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_comerciais', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Registro Comercial',
                'verbose_name_plural': 'Registros Comerciais',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ContatoHistorico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_contato', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data do Contato')),
                ('resultado', models.TextField(help_text='Descrição do resultado do contato', verbose_name='Resultado')),
                ('status_anterior', models.CharField(choices=[('importado', 'Importado'), ('contatado', 'Contatado'), ('conversou', 'Conversou'), ('interesse', 'Interesse'), ('pedido', 'Pedido'), ('perdido', 'Perdido')], max_length=20, verbose_name='Status Anterior')),
                ('status_novo', models.CharField(choices=[('importado', 'Importado'), ('contatado', 'Contatado'), ('conversou', 'Conversou'), ('interesse', 'Interesse'), ('pedido', 'Pedido'), ('perdido', 'Perdido')], max_length=20, verbose_name='Status Novo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contatos_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_contatos', to='crm.registrocomercial', verbose_name='Registro')),
            ],
            options={
                'verbose_name': 'Histórico de Contato',
                'verbose_name_plural': 'Históricos de Contatos',
                'ordering': ['-data_contato'],
            },
        ),
        migrations.AddIndex(
            model_name='registrocomercial',
            index=models.Index(fields=['vendedor', 'status_pipeline'], name='crm_registr_vendedo_321a8a_idx'),
        ),
        migrations.AddIndex(
            model_name='registrocomercial',
            index=models.Index(fields=['vendedor', 'no_kanban'], name='crm_registr_vendedo_b5654c_idx'),
        ),
        migrations.AddIndex(
            model_name='registrocomercial',
            index=models.Index(fields=['codigo_winthor'], name='crm_registr_codigo__e328de_idx'),
        ),
        migrations.AddIndex(
            model_name='contatohistorico',
            index=models.Index(fields=['registro', '-data_contato'], name='crm_contato_registr_939b84_idx'),
        ),
    ]
