# Generated by Django 6.0 on 2026-01-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contatohistorico',
            name='status_anterior',
            field=models.CharField(choices=[('a_trabalhar', 'A Trabalhar'), ('contato_realizado', 'Contato Realizado'), ('interesse', 'Interesse'), ('pedido', 'Pedido'), ('arquivado', 'Arquivado')], max_length=20, verbose_name='Status Anterior'),
        ),
        migrations.AlterField(
            model_name='contatohistorico',
            name='status_novo',
            field=models.CharField(choices=[('a_trabalhar', 'A Trabalhar'), ('contato_realizado', 'Contato Realizado'), ('interesse', 'Interesse'), ('pedido', 'Pedido'), ('arquivado', 'Arquivado')], max_length=20, verbose_name='Status Novo'),
        ),
        migrations.AlterField(
            model_name='registrocomercial',
            name='status_pipeline',
            field=models.CharField(choices=[('a_trabalhar', 'A Trabalhar'), ('contato_realizado', 'Contato Realizado'), ('interesse', 'Interesse'), ('pedido', 'Pedido'), ('arquivado', 'Arquivado')], default='a_trabalhar', max_length=20, verbose_name='Status no Pipeline'),
        ),
    ]
