# Generated by Django 6.0 on 2026-01-05 18:10

from django.db import migrations, models
import crm.models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_contatohistorico_status_anterior_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contatohistorico',
            name='canal_contato',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('telefone', 'Telefone'), ('email', 'E-mail'), ('instagram', 'Instagram'), ('presencial', 'Presencial'), ('outros', 'Outros')], default='whatsapp', max_length=20, verbose_name='Canal do Contato'),
        ),
        migrations.AddField(
            model_name='registrocomercial',
            name='canal_contato',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('telefone', 'Telefone'), ('email', 'E-mail'), ('instagram', 'Instagram'), ('presencial', 'Presencial'), ('outros', 'Outros')], default='whatsapp', help_text='Canal preferencial de comunicação com o lead', max_length=20, verbose_name='Canal de Contato'),
        ),
    ]
