# Generated by Django 6.0 on 2026-01-06 11:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_pipeline_canonico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='registrocomercial',
            index=models.Index(fields=['status_pipeline', '-atualizado_em'], name='crm_registr_status__b74b41_idx'),
        ),
        migrations.AddIndex(
            model_name='registrocomercial',
            index=models.Index(fields=['cidade', 'uf'], name='crm_registr_cidade_097530_idx'),
        ),
        migrations.AddIndex(
            model_name='registrocomercial',
            index=models.Index(fields=['-criado_em'], name='crm_registr_criado__45d58f_idx'),
        ),
    ]
