# Generated by Django 6.0 on 2026-01-06 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_registrocomercial_crm_registr_status__b74b41_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrocomercial',
            name='data_retorno',
            field=models.DateTimeField(blank=True, help_text='Data agendada para próximo contato (follow-up)', null=True, verbose_name='Data de Retorno'),
        ),
    ]
