# Generated by Django 6.0 on 2026-01-11 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_registrocomercial_data_retorno'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrocomercial',
            name='status_cliente',
            field=models.CharField(choices=[('novo', 'Cliente Novo'), ('ativo', 'Cliente Ativo'), ('inativo', 'Cliente Inativo')], default='novo', help_text='Contexto operacional que altera opções de resultado sem mudar o funil', max_length=20, verbose_name='Status do Cliente'),
        ),
    ]
