# Generated by Django 6.0 on 2026-01-11 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_registrocomercial_status_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunilProximoPassoConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coluna_pipeline', models.CharField(choices=[('conta_para_contato', 'Conta para Contato'), ('contato_feito', 'Contato Feito'), ('negociacao_cotacao', 'Negociação / Cotação'), ('pedido_realizado', 'Pedido Realizado'), ('conta_ativa', 'Conta Ativa')], max_length=50, verbose_name='Coluna do Funil')),
                ('status_cliente', models.CharField(choices=[('novo', 'Cliente Novo'), ('ativo', 'Cliente Ativo'), ('inativo', 'Cliente Inativo')], max_length=20, verbose_name='Status do Cliente')),
                ('label', models.CharField(help_text="Ex: 'Tentar contato novamente'", max_length=150, verbose_name='Próximo Passo')),
                ('ativo', models.BooleanField(default=True, help_text='Se marcado, aparece no formulário', verbose_name='Ativo')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='0-9: ordem de exibição no select', verbose_name='Ordem')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Configuração de Próximo Passo',
                'verbose_name_plural': 'Configurações de Próximos Passos',
                'ordering': ['coluna_pipeline', 'status_cliente', 'ordem', 'label'],
                'indexes': [models.Index(fields=['coluna_pipeline', 'status_cliente', 'ativo'], name='crm_funilpr_coluna__e37d19_idx'), models.Index(fields=['ativo'], name='crm_funilpr_ativo_4ac6cb_idx')],
            },
        ),
        migrations.CreateModel(
            name='FunilResultadoConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coluna_pipeline', models.CharField(choices=[('conta_para_contato', 'Conta para Contato'), ('contato_feito', 'Contato Feito'), ('negociacao_cotacao', 'Negociação / Cotação'), ('pedido_realizado', 'Pedido Realizado'), ('conta_ativa', 'Conta Ativa')], max_length=50, verbose_name='Coluna do Funil')),
                ('status_cliente', models.CharField(choices=[('novo', 'Cliente Novo'), ('ativo', 'Cliente Ativo'), ('inativo', 'Cliente Inativo')], max_length=20, verbose_name='Status do Cliente')),
                ('key', models.CharField(help_text="Ex: 'contato_responsavel', 'numero_invalido'", max_length=50, verbose_name='Chave interna (slug)')),
                ('label', models.CharField(help_text='O que aparece no select do vendedor', max_length=150, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, help_text='Se marcado, aparece no formulário', verbose_name='Ativo')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='0-9: ordem de exibição no select', verbose_name='Ordem')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Configuração de Resultado',
                'verbose_name_plural': 'Configurações de Resultados',
                'ordering': ['coluna_pipeline', 'status_cliente', 'ordem', 'key'],
                'indexes': [models.Index(fields=['coluna_pipeline', 'status_cliente', 'ativo'], name='crm_funilre_coluna__8ea6c7_idx'), models.Index(fields=['ativo'], name='crm_funilre_ativo_c6fe16_idx')],
                'unique_together': {('coluna_pipeline', 'status_cliente', 'key')},
            },
        ),
    ]
