# Generated by Django 6.0 on 2026-01-11 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_funilproximopassoconfig_funilresultadoconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='funilresultadoconfig',
            name='proxima_coluna',
            field=models.CharField(choices=[('lead', 'Lead'), ('conta_para_contato', 'Conta para Contato'), ('negociacao_cotacao', 'Negociação / Cotação'), ('conta_ativa', 'Conta Ativa'), ('arquivado', 'Arquivado'), ('manter', 'Manter na mesma coluna')], default='manter', help_text='Para onde o card avança ao escolher este resultado', max_length=50, verbose_name='Próxima Coluna'),
        ),
        migrations.AddField(
            model_name='funilresultadoconfig',
            name='proximo_status_pipeline',
            field=models.CharField(blank=True, help_text='Status técnico do pipeline (auto-preenchido baseado na proxima_coluna)', max_length=50, null=True, verbose_name='Próximo Status Pipeline (interno)'),
        ),
        migrations.AlterField(
            model_name='funilproximopassoconfig',
            name='coluna_pipeline',
            field=models.CharField(choices=[('lead', 'Lead'), ('conta_para_contato', 'Conta para Contato'), ('negociacao_cotacao', 'Negociação / Cotação'), ('conta_ativa', 'Conta Ativa')], max_length=50, verbose_name='Coluna do Funil'),
        ),
        migrations.AlterField(
            model_name='funilresultadoconfig',
            name='coluna_pipeline',
            field=models.CharField(choices=[('lead', 'Lead'), ('conta_para_contato', 'Conta para Contato'), ('negociacao_cotacao', 'Negociação / Cotação'), ('conta_ativa', 'Conta Ativa'), ('arquivado', 'Arquivado')], max_length=50, verbose_name='Coluna do Funil'),
        ),
    ]
